# Generated by Django 5.2.1 on 2025-06-14 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdMenuText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(help_text='A unique key for a menu, e.g., "welcome_menu"', max_length=50)),
                ('menu_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.language')),
            ],
            options={
                'unique_together': {('menu_key', 'language')},
            },
        ),
    ]
