# Generated by Django 5.2.1 on 2025-06-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_seed_all_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="ai_category",
            field=models.CharField(
                blank=True,
                help_text="AI-assigned health category",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="ai_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated summary of symptoms", null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="ai_urgency",
            field=models.CharField(
                blank=True,
                help_text="AI-assigned urgency label",
                max_length=20,
                null=True,
            ),
        ),
    ]
