# Generated by Django 5.2.1 on 2025-07-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_case_ai_category_case_ai_summary_case_ai_urgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="api.agent",
            ),
        ),
    ]
