# Generated by Django 5.1.3 on 2025-07-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_agent_is_active_agent_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
