# Generated by Django 5.1.3 on 2025-07-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_user_otp_user_otp_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="checkout_request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
