# Generated by Django 5.1.3 on 2025-07-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_case_checkout_request_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("assigned_to_agent", "Assigned to Agent"),
                    ("agent_viewed", "Viewed by Agent"),
                    ("agent_action_taken", "Action Taken"),
                    ("referred", "Referred"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("needs_follow_up", "Needs Follow-up"),
                    ("payment_pending", "Payment Pending"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
