# Generated by Django 5.1.3 on 2025-07-18 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_case_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("assigned_to_agent", "Assigned to Agent"),
                    ("agent_viewed", "Viewed by Agent"),
                    ("payment_pending", "Payment Pending"),
                    ("paid", "Paid"),
                    ("agent_action_taken", "Action Taken"),
                    ("referred", "Referred"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("needs_follow_up", "Needs Follow-up"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CaseHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(
                        help_text="A description of the event that occurred.",
                        max_length=255,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="api.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mpesa_receipt_number", models.CharField(max_length=50, unique=True)),
                ("transaction_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.case",
                    ),
                ),
            ],
        ),
    ]
